version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: analysis_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analysis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  knowledge_service:
    build: ./knowledge_service
    container_name: knowledge_service
    command: uvicorn src.main:app --host 0.0.0.0 --port 8007
    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASS: postgres       
      DB_NAME: analysis_db
      DB_PORT: 5432
    ports:
      - "8007:8007"
    depends_on:
      postgres_db:
        condition: service_healthy

  syntax_service:
    build: ./syntax_service
    container_name: syntax_service
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  logic_service:
    build: ./logic_service
    container_name: logic_service
    command: uvicorn src.main:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"

  style_service:
    build: ./style_service
    container_name: style_service
    command: uvicorn src.main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  ml_service:
    build: ./ml_service
    container_name: ml_service
    command: uvicorn src.main:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
  admin_service:
    build: ./admin_service
    container_name: admin_service
    command: uvicorn src.main:app --host 0.0.0.0 --port 8004
    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASS: postgres       
      DB_NAME: analysis_db
      DB_PORT: 5432
    ports:
      - "8004:8004"

  report_service:
    build: ./report_service
    container_name: report_service
    command: uvicorn src.main:app --host 0.0.0.0 --port 8008
    environment:
      DB_HOST: postgres_db
      DB_USER: postgres
      DB_PASS: postgres       
      DB_NAME: analysis_db
      DB_PORT: 5432
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      ADMIN_EMAIL: admin@admin.admin

      SYNTAX_URL: http://syntax_service:8001/analyze
      LOGIC_URL: http://logic_service:8003/analyze
      STYLE_URL: http://style_service:8002/analyze
      ML_URL: http://ml_service:8005/analyze/ml
      KNOWLEDGE_URL: http://knowledge_service:8004/knowledge/lookup/
    ports:
      - "8008:8008"
    depends_on:
      postgres_db:
        condition: service_healthy
      knowledge_service:
        condition: service_started
      syntax_service:
        condition: service_started
      logic_service:
        condition: service_started
      style_service:
        condition: service_started
      ml_service:
        condition: service_started
  frontend:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"         
    depends_on:
      - report_service
      - ml_service
      - admin_service

volumes:
  postgres_data:
